/**
 * Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    COMPANY
 * @subpackage model
 * @author     Rudie Shahinian
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product extends BaseProduct
{
        public function getImages() {
                        $images= Doctrine_Query::create()
                        ->from( 'Images i' )
                        ->select('*')
                        ->leftJoin('i.Productimages p ON i.id = p.images_id')
                        ->where('p.product_id = ?', $this->getId())
                        ->execute();
                return $images;
        }
        public function getCatagories() {
                        $cat= Doctrine_Query::create()
                        ->from( 'Catagory c' )
                        ->select('*')
                        ->leftJoin('c.ProductCatagory p ON c.id = p.catagory_id')
                        ->where('p.product_id = ?', $this->getId())
                        ->execute();
                return $cat;
        }
        public function getPrice($currency = "USD") {
                        $p = Doctrine_Core::getTable('Price')
                        ->createQuery('c')
                        ->where('c.product_id = ?', $this->getId())
                        ->andWhere('c.currency= ?', $currency)
                        ->execute();
                        if ($p && count($p) == 1) {
                                $price = $p[0]->getPrice();
                        }
                        else {
                                $price = false;
                        }
                return $price;
        }
        public function __toString() {
                return $this->getName();
        }
}
